### ISSUE TITLE
Markbot issue

### ISSUE THREAD

**Issue by lexyfh** [lexyfh/css-validation-fixes#1]
So I tried redoing the exercise. I deleted the repository and forked and cloned it again but I'm still getting the exact same issue. I renamed the entire css folder and index file this time as you recommended, but it's still not updating on GitHub.

@abhaysharma

**Comment by abhaysharma** [comment]
@lexyfh the Index.html file and CSS folder names are still using uppercase letter in this repo. Please rename them on your computer push and then rename back to lowercase and push.

**Comment by lexyfh** [comment]
@abhaysharma Yes I know that, I already changed them on my computer so that's why I'm confused that it's still not changing on GitHub.

**Comment by lexyfh** [comment]
<img width="333" alt="Screen Shot 2021-07-16 at 8 44 19 PM" src="https://user-images.githubusercontent.com/84150431/126020918-8fda25f9-7698-4ed3-9533-19306c7b803a.png">

Here is a screenshot of the changes I made, this is my second try at changing the file and folder name, everything has been pushed.

@abhaysharma
